-- CREATE DATABASE Syntax

DROP DATABASE IF EXISTS vezbe;

CREATE DATABASE vezbe;

SHOW CREATE DATABASE vezbe;

CREATE DATABASE vezbe_character_set CHARACTER SET utf8 COLLATE utf8_bin;

SHOW CREATE DATABASE vezbe_character_set;
